server:
  port: 8081
spring:
  application:
    name: user-service
  profiles:
    active: ${ACTIVE_PROFILES:}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URL:http://localhost:8080}
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432}/${DB_NAME:user-service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: ${LOG_LEVEL:info}