spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: my-pet
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:9000/realms/MyPetDev
            user-name-attribute: preferred_username
