version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: my-pet-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    command: start-dev --import-realm
    ports:
      - "9000:8080"
    networks:
      - my-pet
networks:
  my-pet:
    external: true