keycloak:
  enabled: false
  realm: ${KEYCLOAK_REALM:MyPetDev}
  auth-server-url: ${KEYCLOAK_URL:http://localhost:9000}
  resource: ${KEYCLOAK_CLIENT:my-pet}
  bearer-only: true
  admin-user: ${KEYCLOAK_ADMIN_USER:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

server:
  port: 8083
  servlet:
    context-path: /product-service
spring:
  application:
    name: user-service
  profiles:
    active: ${ACTIVE_PROFILES:}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URL:http://localhost:8080}
  mvc:
    log-resolved-exception: false
mongo:
  url: ${MONGO_URL:mongodb://mypet-product:1234@localhost:27017/?authSource=product-service}
logging:
  level:
    root: ${LOG_LEVEL:info}
