version: '3.8'

services:
  database:
    image: postgres:13.5
    container_name: my-pet-database
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-pet
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: my-pet-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    ports:
      - "9000:8080"
    networks:
      - my-pet
    depends_on:
      - database
networks:
  my-pet:
volumes:
  database: