server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/tshen-dev/my-pet.git
          search-paths: configurations
