version: '3.8'

services:
  postgres:
    image: postgres:13.5
    container_name: my-pet-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-pet
  mongo:
    image: mongo:6.0.4
    container_name: my-pet-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo:/etc/mongo
    ports:
      - "27017:27017"
    networks:
      - my-pet
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express:1.0.0-alpha.4
    container_name: my-pet-mongo-express
    restart: always
    ports:
      - "9001:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@my-pet-mongo:27017/
    networks:
      - my-pet
networks:
  my-pet:
    external: true
volumes:
  postgres:
  mongo: