environment: local
server:
  port: 8082

spring:
  application:
    name: notification-service
  profiles:
    active: ${ACTIVE_PROFILES:}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URL:http://localhost:8080}
logging:
  level:
    root: ${LOG_LEVEL:info}