environment: local

keycloak:
  enabled: false
  realm: ${KEYCLOAK_REALM:MyPetDev}
  auth-server-url: ${KEYCLOAK_URL:http://localhost:9000}
  resource: ${KEYCLOAK_CLIENT:my-pet}
  bearer-only: true

server:
  port: 8082
  servlet:
    context-path: /notification-service
notification-service:
  is-simulator: true
spring:
  application:
    name: notification-service
  profiles:
    active: ${ACTIVE_PROFILES:}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URL:http://localhost:8080}
  kafka:
    bootstrap-servers: ${KAFKA_URL:http://localhost:9092}
logging:
  level:
    root: ${LOG_LEVEL:info}
    org.apache.kafka: warn
notification:
  email:
    sender: ${NOTIFICATION_EMAIL_SENDER:}
    password: ${NOTIFICATION_EMAIL_PASSWORD:}
